finance_majordomo/stocks/urls.py
from django.urls import path
from finance_majordomo import views as v
from finance_majordomo.stocks.views \
    import accrual_views, asset_views, search_views, transaction_views

app_name = 'stocks'

urlpatterns = [
    path('', v.index, name='home'),

    path('search/', search_views.Search.as_view(), name='search'),
    path('stocks/', asset_views.Stocks.as_view(), name='stocks'),
    path('stocks/my/', asset_views.PortfolioAssets.as_view(),
         name='users_stocks'),
    path('stocks/add/', asset_views.AddStock.as_view(), name='add_stock'),
    path('stocks/<int:pk>/delete/', asset_views.DeleteStock.as_view(),
         name='delete_asset'),

    path('dividends/', accrual_views.Accruals.as_view(),
         name='accruals'),
    path('dividends/my', accrual_views.UsersDividends.as_view(),
         name='users_dividends'),
    path('dividends/toggle_dividend/<int:pk_accrual>', accrual_views.
         TogglePortfolioDiv.as_view(), name="toggle_portfolio_div"),

    path('transactions/', transaction_views.TransactionList.as_view(),
         name="transactions"),
    path('transactions/my/', transaction_views.UsersTransactionList.as_view(),
         name="user_transactions"),
    path('transactions/create/', transaction_views.AddTransaction.as_view(),
         name="add_transaction"),
    path('transactions/<int:pk>/delete/', transaction_views.
         DeleteTransaction.as_view(), name="delete_transaction")
]

finance_majordomo/urls.py
from django.contrib import admin
from django.urls import path, include

from finance_majordomo import views
from finance_majordomo.users.views import LoginUser, logout_user

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index, name="home"),

    #path('', include("finance_majordomo.stocks.urls")),
    path('', include("finance_majordomo.stocks.urls")),
    path("users/", include("finance_majordomo.users.urls")),
    path("stocks/", include("finance_majordomo.stocks.urls")),
    path("transactions/", include("finance_majordomo.stocks.urls")),
    path("dividends/", include("finance_majordomo.stocks.urls")),
    path("search/", include("finance_majordomo.stocks.urls")),

    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", logout_user, name="logout")
]

finance_majordomo/users/urls.py
from django.urls import path
from finance_majordomo.users import views


urlpatterns = [
    path("", views.UserList.as_view(), name="users"),
    #path("<int:pk>/delete/", views.DeleteUser.as_view(), name="delete_user"),
    #path("<int:pk>/update/", views.UpdateUser.as_view(), name="update_user"),
    path("set_fields/", views.SetFieldsToDisplay.as_view(), name="set_fields"),
    path("create/", views.CreateUser.as_view(), name="create_user"),
    path("add_stock/<int:pk_stock>/", views.AddStockToUser.as_view(),
         name="add_stock_to_user"),
    path("add_asset/<int:pk_asset>/", views.AddAssetToPortfolio.as_view(),
         name="add_asset_to_portfolio"),
    #path("<int:user_id>/add_transaction/<int:stock_id>", views.AddTransaction.as_view(), name="add_transaction"),
]

finance_majordomo/currencies/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class CurrencyRate(models.Model):

    tradedate = models.DateField()
    price_usd = models.DecimalField(max_digits=8, decimal_places=4, null=True)

    is_closed = models.BooleanField(blank=False)
    update_time = models.DateTimeField(blank=True, null=True)

finance_majordomo/stocks/models/accrual_models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from finance_majordomo.stocks.models.asset import Asset
from finance_majordomo.users.models import Portfolio


class Accrual(models.Model):

    creation_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Creation date"))

    asset = models.ForeignKey(
        Asset,
        on_delete=models.CASCADE
    )

    date = models.DateField(
        verbose_name=_("Accrual date")
    )

    #make not null:
    amount = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name=_("Accrual amount for one asset"))

    portfolios = models.ManyToManyField(
        Portfolio,
        through='AccrualsOfPortfolio',
        through_fields=('accrual', 'portfolio'),
        blank=True,
        related_name='accrual',
    )

    class Meta:
        verbose_name = "Начисление"
        verbose_name_plural = "Начисления"
        ordering = ['creation_date', 'asset', 'amount']


class AccrualsOfPortfolio(models.Model):
    portfolio = models.ForeignKey(
        Portfolio,
        on_delete=models.CASCADE,
        null=True
    )

    accrual = models.ForeignKey(
        Accrual,
        on_delete=models.CASCADE,
        null=True
    )

    is_received = models.BooleanField(
        default=False,
        help_text='shows if portfolio got accrual',
        verbose_name='Accrual status'
    )

    class Meta:

        unique_together = ('portfolio', 'accrual')
        verbose_name = "Начисление портфеля"
        verbose_name_plural = "Начисления портфеля"
        ordering = ['accrual']

finance_majordomo/stocks/forms/asset_forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django import forms
from django.utils.translation import gettext_lazy as _
from finance_majordomo.stocks.models.asset import Stock

from common.utils.stocks import validate_ticker, get_asset_description


#to delete
class StockForm(ModelForm):

    ticker = forms.CharField(
        label='Тикер', widget=forms.TextInput(
            attrs={"class": "form-control"})
    )

    class Meta:
        model = Stock
        fields = ['ticker']

    def clean_ticker(self):
        ticker = self.cleaned_data['ticker'].upper()
        #print(ticker, Stock.objects.filter(secid=ticker))
        if Stock.objects.filter(secid=ticker).count() == 1:
            raise ValidationError(_(f"Тикер {ticker} уже добавлен"))

        stock_description = get_asset_description(ticker)

        if not stock_description:
            raise ValidationError(_(f"Ticker {ticker} hasn't been found"))

        if stock_description.get("GROUP") not in ["stock_shares", "stock_bonds"]:
            raise ValidationError(_(f"Only shares and bonds accepted"))

        self.cleaned_data['stock_description'] = stock_description
        return ticker

finance_majordomo/stocks/forms/search_forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django import forms
from django.utils.translation import gettext_lazy as _
from finance_majordomo.stocks.models.asset import Stock


class SearchForm(forms.Form):

    search_data = forms.CharField(
        label='Ticker, ISIN or name',
        widget=forms.TextInput(attrs={"class": "form-control"})
    )


class SearchResultForm(forms.Form):

    secid = forms.CharField(disabled=True)
    shortname = forms.CharField(disabled=True)
    regnumber = forms.CharField(disabled=True)
    name = forms.CharField(disabled=True)
    isin = forms.CharField(disabled=True, widget=forms.TextInput(attrs={"class": "form-label"}))
    type = forms.CharField(disabled=True, widget=forms.HiddenInput)
    group = forms.CharField(disabled=True, widget=forms.HiddenInput)
    primary_boardid = forms.CharField(disabled=True, widget=forms.HiddenInput)

finance_majordomo/stocks/views/accrual_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.views import View
from django.views.generic import ListView
from django.utils.translation import gettext_lazy as _

from finance_majordomo.stocks.models.accrual_models import Accrual
from finance_majordomo.stocks.services.accrual_services.\
    dividend_model_management_services \
    import execute_toggle_portfolio_accrual_service
from finance_majordomo.stocks.services.accrual_services.dividend_view_services \
    import execute_portfolio_accrual_view_context_service


class Accruals(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Accrual
    template_name = 'dividends/dividend_list.html'
    context_object_name = 'accrual'

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)
        context['page_title'] = _("Accruals list")

        portfolio = self.request.user.current_portfolio

        accruals_data = \
            execute_portfolio_accrual_view_context_service(portfolio, 90)

        context['accrual_list'] = accruals_data.get('accrual_list')
        context['total_results'] = accruals_data.get('total_results')

        return context


class UsersDividends(LoginRequiredMixin, ListView):
    pass


class TogglePortfolioDiv(SuccessMessageMixin, LoginRequiredMixin, View):
    model = Accrual
    login_url = 'login'

    def get(self, request, *args, **kwargs):

        portfolio = request.user.current_portfolio
        accrual = Accrual.objects.get(id=kwargs.get('pk_accrual'))

        try:
            execute_toggle_portfolio_accrual_service(accrual, portfolio)

        except Exception as e:
            print(e, ' in ', execute_toggle_portfolio_accrual_service)

        return redirect('stocks:accruals')

finance_majordomo/stocks/views/asset_views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import ProtectedError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView
from django.utils.translation import gettext_lazy as _

from finance_majordomo.stocks.forms.asset_forms import StockForm
from finance_majordomo.stocks.models.asset import Asset
from finance_majordomo.stocks.services.asset_services.\
    asset_model_management_services \
    import create_asset_obj_from_description
from finance_majordomo.stocks.services.\
    asset_services.asset_view_services \
    import PortfolioAssetsViewContextService,\
    execute_portfolio_asset_view_context_service



class Stocks(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Asset
    template_name = 'stocks/stock_list.html'
    context_object_name = 'stock'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = _("Stock list")
        context['stock_list'] = Asset.objects.all()
        return context


class PortfolioAssets(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Asset
    template_name = 'stocks/user_stock_list.html'
    context_object_name = 'stock'

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)

        portfolio_assets_data = execute_portfolio_asset_view_context_service(
            self.request.user.current_portfolio)

        asset_list = portfolio_assets_data.get('asset_list')
        total_results = portfolio_assets_data.get('total_results')

        context['page_title'] = self.request.user.username + " " + _(
            "stock list")
        context['fields_to_display'] = self.request.user.usersettings
        context['current_portfolio'] = self.request.user.current_portfolio
        context['asset_list'] = asset_list
        context['total_results'] = total_results

        return context


class AddStock(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    login_url = 'login'
    form_class = StockForm
    template_name = 'base_create_and_update.html'

    success_url = reverse_lazy('stocks:stocks')
    success_message = _("Stock has been successfully added!")

    self_url = reverse_lazy('add_stock')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = _("Add new stock")
        context['button_text'] = _("Add")
        return context

    def post(self, request, *args, **kwargs):

        form = StockForm(request.POST)

        if form.is_valid():

            stock_description = form.cleaned_data.get('stock_description')
            create_asset_obj_from_description(stock_description)

            messages.success(request, self.success_message)
            return redirect(self.success_url)
        return super().post(request, *args, **kwargs)


    # # не используется?
    # @staticmethod
    # def actualize_stock_data(stock, start_date=None):
    # 
    #     today = datetime.datetime.today().strftime('%Y-%m-%d')
    #     today = datetime.datetime.strptime(today, '%Y-%m-%d')
    #     last_day = datetime.datetime.strptime(start_date, '%Y-%m-%d')
    # 
    #     json_current_stock_data = json.loads(stock.stock_data)
    # 
    #     stock_board_history = get_asset_board_history(
    #         stock.secid, start_date)
    #     json_stock_board_data = json.loads(
    #         make_json_trade_info_dict(stock_board_history))
    # 
    #     #print('======')
    #     #print(json_stock_data['TRADEINFO'])
    #     #print('#======#')
    #     #print(json_stock_board_data, type(json_stock_board_data))
    #     #print(json_stock_board_data['TRADEINFO'])
    #     #print('##======##')
    # 
    #     json_current_stock_data['TRADEINFO'].update(
    #         json_stock_board_data['TRADEINFO'])
    # 
    #     #print('##########')
    #     #print(json_stock_data)
    #     #print('###########')
    #     #print('1', json_stock_data.keys())
    #     #print('2', json_stock_data['TRADEINFO'].keys())
    # 
    #     stock_data = json.dumps(json_current_stock_data)
    #     #stock.stock_data = stock_data
    #     #stock.save()
    # 
    #     return stock


class DeleteStock(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    login_url = 'login'
    model = Asset
    template_name = "base_delete.html"
    success_url = reverse_lazy('stocks:stocks')
    success_message = _("Stock has been successfully deleted!")

    # def dispatch(self, request, *args, **kwargs):
    #     if self.get_object().creator.id == request.user.id \
    #             or request.user.is_staff:
    #         return super().dispatch(request, *args, **kwargs)
    #     messages.error(request, _('You can delete only your labels'))
    #     return redirect('labels')

    def post(self, request, *args, **kwargs):

        try:
            return super().post(request, *args, **kwargs)
        except ProtectedError:
            messages.error(request, _('error'))
            return redirect('stocks:stocks')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = _("Delete stock")
        context['button_text'] = _("Delete")
        context['delete_object'] = str(
            Asset.objects.get(id=self.get_object().id))
        print(context['delete_object'])
        return context

finance_majordomo/stocks/views/search_views.py
from django.views import View
from common.utils.stocks import get_security
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from finance_majordomo.stocks.forms.search_forms import SearchForm
from django.utils.translation import gettext_lazy as _


class Search(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        form = SearchForm()

        context = {
            'page_title': _("Search for assets"),
            'button_text': _("Search"),
            'form': form
        }

        return render(
            request,
            'base_create_and_update.html',
            context=context
        )

    def post(self, request, *args, **kwargs):
        form = SearchForm(request.POST)

        allowed_groups = ['stock_shares',
                          'stock_bonds',
                          # 'stock_ppif'
                          ]

        allowed_boardids = [
            'TQBR',
            'TQOB',
            'TQCB',
        ]

        if form.is_valid():
            search_data = form.cleaned_data.get('search_data')

            search_result = get_security(search_data)

            search_result_list = list(filter(
                lambda sec: sec['is_traded'] and
                            sec['group'] in allowed_groups and
                            sec['primary_boardid'] in allowed_boardids and
                            sec['secid'].isupper(),
                search_result))

            # forms_list = []
            # 
            # for search_item in search_result_list:
            #     forms_list.append(
            #         SearchResultForm(initial={
            #             'secid': search_item.get('secid'),
            #             'shortname': search_item.get('shortname'),
            #             'regnumber': search_item.get('regnumber'),
            #             'name': search_item.get('name'),
            #             'isin': search_item.get('isin'),
            #             'type': search_item.get('type'),
            #             'group': search_item.get('group'),
            #             'primary_boardid': search_item.get('primary_boardid'),
            #         })
            #     )

            context = {
                'page_title': _("Search results"),
                'search_result_list':
                    search_result_list if search_result_list else None,
            }

            return render(
                request,
                'search/search_result_list.html',
                context=context
            )

finance_majordomo/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'base.html', context={
        "who": "person",
    })

finance_majordomo/templates/dividends/_cards_deck_dividends.html
{% load i18n %}
<div class="container-xxl px-4">
    <div class="card-deck d-flex justify-content-between">

        <div class="card border-info bg-light mb-3 d-flex" style="max-width: 28rem;">
            <div class="card-header border-info">
                  <h5 class="mb-0"><b>{% translate "Dividends for the holding period" %}</b></h5>
            </div>
            <div class="card-body">
                <h4 class="card-title">{{ total_results.total_divs_payable }} RUR</h4>
                <p class="card-text">Including tax payment</p>
            </div>
        </div>

        <div class="card border-info bg-light mb-3" style="max-width: 28rem;">
            <div class="card-header border-info">
                <h4 class="mb-0"><b>{% translate "Dividends received" %}</b></h4>
            </div>
            <div class="card-body">
                <h4 class="card-title">{{ total_results.total_divs_received }} RUR</h4>
                <p class="card-text">Including tax payment</p>
            </div>
        </div>

        <div class="card border-info bg-light mb-3" style="max-width: 28rem;">
            <div class="card-header border-info">
                <h4 class="mb-0"><b>{% translate "Upcoming payments" %}</b></h4>
            </div>
            <div class="card-body">
                <h4 class="card-title">{{ total_results.total_divs_upcoming }} RUR</h4>
            </div>
        </div>

    </div>
</div> 

finance_majordomo/templates/dividends/dividend_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <div class="container wrapper flex-grow-1">
        <h1 class="my-4">{{ page_title }}</h1>
    
        {% include 'dividends/_cards_deck_dividends.html' %}

        <table id="myDivDataTable" class="table table-striped">
           <thead>
                <tr>

                    <th>{% translate "Ticker" %}</th>
                    <th>{% translate "Quantity" %}</th>
                    <th>{% translate "Date" %}</th>
                    <th>{% translate "Dividend for each" %}</th>
                    
                    <th>{% translate "Dividends for all" %}</th>
                    <th></th>

                </tr>
            </thead>

            <tbody>

                {% for dividend in accrual_list %}
                <tr id="dividend_id_{{ dividend.id }}"> 
                    <td>{{ dividend.asset_name }}</td>
                    <td>{{ dividend.asset_quantity }}</td>
                    <td>{{ dividend.date }}</td>
                    <td>{{ dividend.amount }}</td>
                    
                    <td>{{ dividend.sum }}</td>
                
                    {% if dividend.is_upcoming %}
                    <td>
                        <div class="d-flex justify-content-left">
                            <a class="btn btn-info btn-sm" role="button">{% translate "Upcoming accrual" %}</a>
                        </div>
                    </td>    
                    {% elif dividend.is_received %}
                    <td>
                        <div class="d-flex justify-content-left">
                            <a class="btn btn-success btn-sm" href="{% url "stocks:toggle_portfolio_div" dividend.id %}" role="button">{% translate "Remove dividend" %}</a>
                        </div>
                    </td>
                    {% else %}
                    <td>
                        <div class="d-flex justify-content-left">
                            <a class="btn btn-primary btn-sm" href="{% url "stocks:toggle_portfolio_div" dividend.id %}" role="button">{% translate "Get dividend" %}</a>
                        </div>
                    </td>
                    {% endif %}
                
                </tr>
                {% endfor %}
                
            </tbody>
        </table>
    </div>

{% endblock content %}

finance_majordomo/templates/dividends/user_dividend_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <div class="container wrapper flex-grow-1">
        <h1 class="my-4">{{ page_title }}</h1>

        <table id="myTable" class="table table-striped">
           <thead>
                <tr>
                    {% if fields_to_display.ticker %}
                    <th>{% translate "Ticker" %}</th>
                    {% endif %}

                    {% if fields_to_display.name %}
                    <th>{% translate "Date" %}</th>
                    {% endif %}

                    {% if fields_to_display.currency %}
                    <th>{% translate "Dividend" %}</th>
                    {% endif %}

                    {% if fields_to_display.quantity %}
                    <th>{% translate "Total Dividend" %}</th>
                    {% endif %}

                    <th></th>

                </tr>
            </thead>

            <tbody method="get">
                {% for stock in stock_list %}
                <tr>
                    {% if fields_to_display.ticker %}
                    <td>{{ dividend.ticker }}</td>
                    {% endif %}

                    {% if fields_to_display.name %}
                    <td>{{ dividend.date }}</td>
                    {% endif %}

                    {% if fields_to_display.currency %}
                    <td>{{ dividend.for_stock }}</td>
                    {% endif %}

                    {% if fields_to_display.quantity %}
                    <td>{{ dividend.for_all }}</td>
                    {% endif %}
                
                    <td>
                        <div class="d-flex justify-content-left">
                            <a class="btn btn-primary btn-sm" href="{% url "add_transaction" stock.id %}" role="button">{% translate "Add transaction" %}</a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}