finance_majordomo/stocks/urls.py
from django.urls import path
from finance_majordomo import views as v
from finance_majordomo.stocks.views \
    import accrual_views, asset_views, search_views, transaction_views

app_name = 'stocks'

urlpatterns = [
    path('', v.index, name='home'),

    path('search/', search_views.Search.as_view(), name='search'),
    path('stocks/', asset_views.Stocks.as_view(), name='stocks'),
    path('stocks/my/', asset_views.PortfolioAssets.as_view(),
         name='users_stocks'),
    path('stocks/add/', asset_views.AddStock.as_view(), name='add_stock'),
    path('stocks/<int:pk>/delete/', asset_views.DeleteStock.as_view(),
         name='delete_asset'),

    path('dividends/', accrual_views.Accruals.as_view(),
         name='accruals'),
    path('dividends/my', accrual_views.UsersDividends.as_view(),
         name='users_dividends'),
    path('dividends/toggle_dividend/<int:pk_accrual>', accrual_views.
         TogglePortfolioDiv.as_view(), name="toggle_portfolio_div"),

    path('transactions/', transaction_views.TransactionList.as_view(),
         name="transactions"),
    path('transactions/my/', transaction_views.UsersTransactionList.as_view(),
         name="user_transactions"),
    path('transactions/create/', transaction_views.AddTransaction.as_view(),
         name="add_transaction"),
    path('transactions/<int:pk>/delete/', transaction_views.
         DeleteTransaction.as_view(), name="delete_transaction")
]

finance_majordomo/urls.py
from django.contrib import admin
from django.urls import path, include

from finance_majordomo import views
from finance_majordomo.users.views import LoginUser, logout_user

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index, name="home"),

    #path('', include("finance_majordomo.stocks.urls")),
    path('', include("finance_majordomo.stocks.urls")),
    path("users/", include("finance_majordomo.users.urls")),
    path("stocks/", include("finance_majordomo.stocks.urls")),
    path("transactions/", include("finance_majordomo.stocks.urls")),
    path("dividends/", include("finance_majordomo.stocks.urls")),
    path("search/", include("finance_majordomo.stocks.urls")),

    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", logout_user, name="logout")
]

finance_majordomo/users/urls.py
from django.urls import path
from finance_majordomo.users import views


urlpatterns = [
    path("", views.UserList.as_view(), name="users"),
    #path("<int:pk>/delete/", views.DeleteUser.as_view(), name="delete_user"),
    #path("<int:pk>/update/", views.UpdateUser.as_view(), name="update_user"),
    path("set_fields/", views.SetFieldsToDisplay.as_view(), name="set_fields"),
    path("create/", views.CreateUser.as_view(), name="create_user"),
    path("add_stock/<int:pk_stock>/", views.AddStockToUser.as_view(),
         name="add_stock_to_user"),
    path("add_asset/<int:pk_asset>/", views.AddAssetToPortfolio.as_view(),
         name="add_asset_to_portfolio"),
    #path("<int:user_id>/add_transaction/<int:stock_id>", views.AddTransaction.as_view(), name="add_transaction"),
]

finance_majordomo/currencies/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class CurrencyRate(models.Model):

    tradedate = models.DateField()
    price_usd = models.DecimalField(max_digits=8, decimal_places=4, null=True)

    is_closed = models.BooleanField(blank=False)
    update_time = models.DateTimeField(blank=True, null=True)

finance_majordomo/stocks/models/accrual_models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from finance_majordomo.stocks.models.asset import Asset
from finance_majordomo.users.models import Portfolio


class Accrual(models.Model):

    creation_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Creation date"))

    asset = models.ForeignKey(
        Asset,
        on_delete=models.CASCADE
    )

    date = models.DateField(
        verbose_name=_("Accrual date")
    )

    #make not null:
    amount = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        verbose_name=_("Accrual amount for one asset"))

    portfolios = models.ManyToManyField(
        Portfolio,
        through='AccrualsOfPortfolio',
        through_fields=('accrual', 'portfolio'),
        blank=True,
        related_name='accrual',
    )

    class Meta:
        verbose_name = "Начисление"
        verbose_name_plural = "Начисления"
        ordering = ['creation_date', 'asset', 'amount']


class AccrualsOfPortfolio(models.Model):
    portfolio = models.ForeignKey(
        Portfolio,
        on_delete=models.CASCADE,
        null=True
    )

    accrual = models.ForeignKey(
        Accrual,
        on_delete=models.CASCADE,
        null=True
    )

    is_received = models.BooleanField(
        default=False,
        help_text='shows if portfolio got accrual',
        verbose_name='Accrual status'
    )

    class Meta:

        unique_together = ('portfolio', 'accrual')
        verbose_name = "Начисление портфеля"
        verbose_name_plural = "Начисления портфеля"
        ordering = ['accrual']

finance_majordomo/stocks/forms/asset_forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django import forms
from django.utils.translation import gettext_lazy as _
from finance_majordomo.stocks.models.asset import Stock

from common.utils.stocks import validate_ticker, get_asset_description


#to delete
class StockForm(ModelForm):

    ticker = forms.CharField(
        label='Тикер', widget=forms.TextInput(
            attrs={"class": "form-control"})
    )

    class Meta:
        model = Stock
        fields = ['ticker']

    def clean_ticker(self):
        ticker = self.cleaned_data['ticker'].upper()
        #print(ticker, Stock.objects.filter(secid=ticker))
        if Stock.objects.filter(secid=ticker).count() == 1:
            raise ValidationError(_(f"Тикер {ticker} уже добавлен"))

        stock_description = get_asset_description(ticker)

        if not stock_description:
            raise ValidationError(_(f"Ticker {ticker} hasn't been found"))

        if stock_description.get("GROUP") not in ["stock_shares", "stock_bonds"]:
            raise ValidationError(_(f"Only shares and bonds accepted"))

        self.cleaned_data['stock_description'] = stock_description
        return ticker

finance_majordomo/stocks/forms/search_forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django import forms
from django.utils.translation import gettext_lazy as _
from finance_majordomo.stocks.models.asset import Stock


class SearchForm(forms.Form):

    search_data = forms.CharField(
        label='Ticker, ISIN or name',
        widget=forms.TextInput(attrs={"class": "form-control"})
    )


class SearchResultForm(forms.Form):

    secid = forms.CharField(disabled=True)
    shortname = forms.CharField(disabled=True)
    regnumber = forms.CharField(disabled=True)
    name = forms.CharField(disabled=True)
    isin = forms.CharField(disabled=True, widget=forms.TextInput(attrs={"class": "form-label"}))
    type = forms.CharField(disabled=True, widget=forms.HiddenInput)
    group = forms.CharField(disabled=True, widget=forms.HiddenInput)
    primary_boardid = forms.CharField(disabled=True, widget=forms.HiddenInput)

finance_majordomo/stocks/views/accrual_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.views import View
from django.views.generic import ListView
from django.utils.translation import gettext_lazy as _

from finance_majordomo.stocks.models.accrual_models import Accrual
from finance_majordomo.stocks.services.accrual_services.\
    dividend_model_management_services \
    import execute_toggle_portfolio_accrual_service
from finance_majordomo.stocks.services.accrual_services.dividend_view_services \
    import execute_portfolio_accrual_view_context_service


class Accruals(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Accrual
    template_name = 'dividends/dividend_list.html'
    context_object_name = 'accrual'

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)
        context['page_title'] = _("Accruals list")

        portfolio = self.request.user.current_portfolio

        accruals_data = \
            execute_portfolio_accrual_view_context_service(portfolio, 90)

        context['accrual_list'] = accruals_data.get('accrual_list')
        context['total_results'] = accruals_data.get('total_results')

        return context


class UsersDividends(LoginRequiredMixin, ListView):
    pass


class TogglePortfolioDiv(SuccessMessageMixin, LoginRequiredMixin, View):
    model = Accrual
    login_url = 'login'

    def get(self, request, *args, **kwargs):

        portfolio = request.user.current_portfolio
        accrual = Accrual.objects.get(id=kwargs.get('pk_accrual'))

        try:
            execute_toggle_portfolio_accrual_service(accrual, portfolio)

        except Exception as e:
            print(e, ' in ', execute_toggle_portfolio_accrual_service)

        return redirect('stocks:accruals')

finance_majordomo/stocks/views/asset_views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import ProtectedError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView
from django.utils.translation import gettext_lazy as _

from finance_majordomo.stocks.forms.asset_forms import StockForm
from finance_majordomo.stocks.models.asset import Asset
from finance_majordomo.stocks.services.asset_services.\
    asset_model_management_services \
    import create_asset_obj_from_description
from finance_majordomo.stocks.services.\
    asset_services.asset_view_services \
    import PortfolioAssetsViewContextService,\
    execute_portfolio_asset_view_context_service



class Stocks(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Asset
    template_name = 'stocks/stock_list.html'
    context_object_name = 'stock'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = _("Stock list")
        context['stock_list'] = Asset.objects.all()
        return context


class PortfolioAssets(LoginRequiredMixin, ListView):
    login_url = 'login'
    model = Asset
    template_name = 'stocks/user_stock_list.html'
    context_object_name = 'stock'

    def get_context_data(self, *, object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)

        portfolio_assets_data = execute_portfolio_asset_view_context_service(
            self.request.user.current_portfolio)

        asset_list = portfolio_assets_data.get('asset_list')
        total_results = portfolio_assets_data.get('total_results')

        context['page_title'] = self.request.user.username + " " + _(
            "stock list")
        context['fields_to_display'] = self.request.user.usersettings
        context['current_portfolio'] = self.request.user.current_portfolio
        context['asset_list'] = asset_list
        context['total_results'] = total_results

        return context


class AddStock(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    login_url = 'login'
    form_class = StockForm
    template_name = 'base_create_and_update.html'

    success_url = reverse_lazy('stocks:stocks')
    success_message = _("Stock has been successfully added!")

    self_url = reverse_lazy('add_stock')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = _("Add new stock")
        context['button_text'] = _("Add")
        return context

    def post(self, request, *args, **kwargs):

        form = StockForm(request.POST)

        if form.is_valid():

            stock_description = form.cleaned_data.get('stock_description')
            create_asset_obj_from_description(stock_description)

            messages.success(request, self.success_message)
            return redirect(self.success_url)
        return super().post(request, *args, **kwargs)


    # # не используется?
    # @staticmethod
    # def actualize_stock_data(stock, start_date=None):
    # 
    #     today = datetime.datetime.today().strftime('%Y-%m-%d')
    #     today = datetime.datetime.strptime(today, '%Y-%m-%d')
    #     last_day = datetime.datetime.strptime(start_date, '%Y-%m-%d')
    # 
    #     json_current_stock_data = json.loads(stock.stock_data)
    # 
    #     stock_board_history = get_asset_board_history(
    #         stock.secid, start_date)
    #     json_stock_board_data = json.loads(
    #         make_json_trade_info_dict(stock_board_history))
    # 
    #     #print('======')
    #     #print(json_stock_data['TRADEINFO'])
    #     #print('#======#')
    #     #print(json_stock_board_data, type(json_stock_board_data))
    #     #print(json_stock_board_data['TRADEINFO'])
    #     #print('##======##')
    # 
    #     json_current_stock_data['TRADEINFO'].update(
    #         json_stock_board_data['TRADEINFO'])
    # 
    #     #print('##########')
    #     #print(json_stock_data)
    #     #print('###########')
    #     #print('1', json_stock_data.keys())
    #     #print('2', json_stock_data['TRADEINFO'].keys())
    # 
    #     stock_data = json.dumps(json_current_stock_data)
    #     #stock.stock_data = stock_data
    #     #stock.save()
    # 
    #     return stock


class DeleteStock(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    login_url = 'login'
    model = Asset
    template_name = "base_delete.html"
    success_url = reverse_lazy('stocks:stocks')
    success_message = _("Stock has been successfully deleted!")

    # def dispatch(self, request, *args, **kwargs):
    #     if self.get_object().creator.id == request.user.id \
    #             or request.user.is_staff:
    #         return super().dispatch(request, *args, **kwargs)
    #     messages.error(request, _('You can delete only your labels'))
    #     return redirect('labels')

    def post(self, request, *args, **kwargs):

        try:
            return super().post(request, *args, **kwargs)
        except ProtectedError:
            messages.error(request, _('error'))
            return redirect('stocks:stocks')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = _("Delete stock")
        context['button_text'] = _("Delete")
        context['delete_object'] = str(
            Asset.objects.get(id=self.get_object().id))
        print(context['delete_object'])
        return context

finance_majordomo/stocks/views/search_views.py
from django.views import View
from common.utils.stocks import get_security
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from finance_majordomo.stocks.forms.search_forms import SearchForm
from django.utils.translation import gettext_lazy as _


class Search(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        form = SearchForm()

        context = {
            'page_title': _("Search for assets"),
            'button_text': _("Search"),
            'form': form
        }

        return render(
            request,
            'base_create_and_update.html',
            context=context
        )

    def post(self, request, *args, **kwargs):
        form = SearchForm(request.POST)

        allowed_groups = ['stock_shares',
                          'stock_bonds',
                          # 'stock_ppif'
                          ]

        allowed_boardids = [
            'TQBR',
            'TQOB',
            'TQCB',
        ]

        if form.is_valid():
            search_data = form.cleaned_data.get('search_data')

            search_result = get_security(search_data)

            search_result_list = list(filter(
                lambda sec: sec['is_traded'] and
                            sec['group'] in allowed_groups and
                            sec['primary_boardid'] in allowed_boardids and
                            sec['secid'].isupper(),
                search_result))

            # forms_list = []
            # 
            # for search_item in search_result_list:
            #     forms_list.append(
            #         SearchResultForm(initial={
            #             'secid': search_item.get('secid'),
            #             'shortname': search_item.get('shortname'),
            #             'regnumber': search_item.get('regnumber'),
            #             'name': search_item.get('name'),
            #             'isin': search_item.get('isin'),
            #             'type': search_item.get('type'),
            #             'group': search_item.get('group'),
            #             'primary_boardid': search_item.get('primary_boardid'),
            #         })
            #     )

            context = {
                'page_title': _("Search results"),
                'search_result_list':
                    search_result_list if search_result_list else None,
            }

            return render(
                request,
                'search/search_result_list.html',
                context=context
            )

finance_majordomo/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'base.html', context={
        "who": "person",
    })

finance_majordomo/templates/base.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load bootstrap4 %}
{% load static %}

<!-- Current language: {{ LANGUAGE_CODE }} -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% bootstrap_css %}
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        

        <title>{% translate "Financial majordomo" %}</title>
    </head>
  
    <body class="d-flex flex-column min-vh-100">
    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3 ">
            <a class="navbar-brand"
               href="{% url 'stocks:home' %}">{% translate "Financial majordomo" %}</a>
            <button class="navbar-toggler" data-toggle="collapse"
                    data-target="navbarToggleExternalContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
                <ul class="navbar-nav mr-auto">

            
                    {% if request.user.is_authenticated %}
                        
                        {% if request.user.is_staff %}
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{% url 'users' %}">{% translate "Users" %}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{% url 'stocks:stocks' %}">{% translate "Stocks" %}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"
                                   href="{% url 'stocks:user_transactions' %}">{% translate "My Transactions" %}</a>
                            </li>
                        {% endif %}
                        
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{% url 'stocks:users_stocks' %}">{% translate "Portfolio" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{% url 'stocks:transactions' %}">{% translate "Transactions" %}</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link"
                               href="{% url 'stocks:accruals' %}">{% translate "Accruals" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{% url 'stocks:search' %}">{% translate "Search" %}</a>
                        </li>
                    {% endif %}


            {% comment %}
            ЗАКОММЕНТИРОВАНО
            <li class="nav-item">
                <a class="nav-link" href="{% url 'statuses' %}">{% translate "Statuses" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tasks' %}">{% translate "Tasks" %}</a>
            </li>
            {% endcomment %}

                </ul>
                <ul class="navbar-nav">
                    {% if request.user.is_authenticated %}
                        <span class="navbar-brand">
                            {{ request.user.username }}
                        </span>
                        <li class="nav-item">
                            <a class="btn btn-primary ml-3" href="{% url 'logout' %}">{% translate "Logout" %}</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="btn btn-outline-secondary" href="{% url 'login' %}">{% translate "Login" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-primary ml-3" href="{% url 'create_user' %}">{% translate "Sign up" %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    {% endblock navbar %}
    
    <div class="container-fluid h-100">
        {% bootstrap_messages %}
        {% block content %}
            
            <h1 class="my-4">{% translate "Hello!" %} {{ who }}!</h1>
        {% endblock content %}
    </div>
    
    <div class="container">
        {% block footer %}
            <div class="my-5 pt-4 border-top">
                <a target="_blank" href="https://t.me/Nedashkovskii">@Nedashkovsky</a>
            </div>
        {% endblock footer %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js"></script>
    {% bootstrap_javascript %}
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#myDataTable').DataTable({
                paging: false,
                
                {#pageLength : 50,#}
                {#lengthMenu: [[50, 100], [50, 100]]#}
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#myDivDataTable').DataTable({
                paging: false,
                info: false,
                order: [[2, 'desc']],
            });
        });
    </script>
    
{#    <script>#}
{#        $(function () {#}
{#            $('#myDivDataTable tr').on('click', function () {#}
{#                $.post({#}
{#                    url: "{% url "add_div_to_user" 82 %}",#}
{#                    window.print(),#}
{#                    data: JSON.stringify(link),#}
{#                    contentType: "application/json; charset=utf-8",#}
{#                    dataType: "json",#}
{#                    success: function (data) {#}
{#                        let button = $('#user-table-select-all')#}
{#                    },#}
{#                })#}
{#            });#}
{#    </script>#}
    
    </body>
</html>

finance_majordomo/templates/base_create_and_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
            <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                    <div class="row justify-content-center">
                        <div class="col-md-12 col-lg-8 col-xl-6 order-2 order-lg-1">
                  
                            <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">{{ page_title }}</p>

                            <form method="post">
                                {% csrf_token %}
{#                                {% bootstrap_form_errors form %}#}
                                {% bootstrap_form form %}
                                
                                <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                    {% bootstrap_button button_text button_class="btn btn-primary btn-lg" %}
                                </div>
                            </form>
                  
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

finance_majordomo/templates/base_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block content %}    
    <div class="card-body p-md-5 align-items-center">
        <h1 class="my-4">{{ page_title }}</h1>
        
        <form method="post">{% csrf_token %}
            <p>{% translate "Are you sure you want to delete" %} {{ delete_object }}?</p>
            {% bootstrap_form_errors form %}
            <input class="btn btn-danger" type="submit" value="{% translate "Yes, delete" %}">
        </form>
    </div>
    
{% endblock content %}

finance_majordomo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Hello, {{ who }}!</h1>
</body>
</html>